services:
  caddy:
    image: caddy:latest
    ports:
    - 8080:80
    - 8000:8000
    - 443:443
    restart: unless-stopped
    volumes:
    - ./Caddyfile:/etc/caddy/Caddyfile
  celery-db:
    environment:
    - POSTGRES_DB=celery
    - POSTGRES_USER=celery
    - POSTGRES_PASSWORD=password
    image: postgres
    restart: always
    volumes:
    - celery-db-OasisData:/var/lib/postgresql/data:rw
  rabbit:
    environment:
    - RABBITMQ_DEFAULT_USER=rabbit
    - RABBITMQ_DEFAULT_PASS=rabbit
    image: rabbitmq:3.8.14-management
    restart: always
  server:
    environment:
    - OASIS_ADMIN_USER=${OASIS_ADMIN_USER:-admin}
    - OASIS_ADMIN_PASS=${OASIS_ADMIN_PASS:-password}
    - OASIS_DEBUG=1
    - OASIS_RABBIT_HOST=rabbit
    - OASIS_RABBIT_PORT=5672
    - OASIS_RABBIT_USER=rabbit
    - OASIS_RABBIT_PASS=rabbit
    - OASIS_SERVER_DB_HOST=server-db
    - OASIS_SERVER_DB_PASS=oasis
    - OASIS_SERVER_DB_USER=oasis
    - OASIS_SERVER_DB_NAME=oasis
    - OASIS_SERVER_DB_PORT=5432
    - OASIS_SERVER_DB_ENGINE=django.db.backends.postgresql_psycopg2
    - OASIS_CELERY_DB_ENGINE=db+postgresql+psycopg2
    - OASIS_CELERY_DB_HOST=celery-db
    - OASIS_CELERY_DB_PASS=password
    - OASIS_CELERY_DB_USER=celery
    - OASIS_CELERY_DB_NAME=celery
    - OASIS_CELERY_DB_PORT=5432
    - STARTUP_RUN_MIGRATIONS=true
    image: coreoasis/api_server:2.3.5
    command: ["./wsgi/run-wsgi.sh"]
    links:
    - server-db
    - celery-db
    - rabbit
    restart: always
    volumes:
    - filestore-OasisData:/shared-fs:rw
  server-db:
    environment:
    - POSTGRES_DB=oasis
    - POSTGRES_USER=oasis
    - POSTGRES_PASSWORD=oasis
    image: postgres
    restart: always
    volumes:
    - server-db-OasisData:/var/lib/postgresql/data:rw
  ui:
    environment:
    - API_IP=server
    - API_PORT=8000
    - API_VERSION=v1
    - API_SHARE_FILEPATH=./downloads
    - OASIS_ENVIRONMENT=oasis_localhost
    image: coreoasis/oasisui_app:1.11.7
    restart: always
  worker-afeq_2019:
    build:
      context: .
      dockerfile_inline: |-
        FROM coreoasis/model_worker:2.3.5
        USER root
        RUN ln -s /home/worker/.local /root/.local
        RUN pip3 install msoffcrypto-tool openpyxl
    environment:
    - OASIS_MODEL_SUPPLIER_ID=CatRisk
    - OASIS_MODEL_ID=AFEQ_2019
    - OASIS_MODEL_VERSION_ID=R.1.2.1.G
    - OASIS_RABBIT_HOST=rabbit
    - OASIS_RABBIT_PORT=5672
    - OASIS_RABBIT_USER=rabbit
    - OASIS_RABBIT_PASS=rabbit
    - OASIS_SERVER_DB_ENGINE=django.db.backends.postgresql_psycopg2
    - OASIS_CELERY_DB_ENGINE=db+postgresql+psycopg2
    - OASIS_CELERY_DB_HOST=celery-db
    - OASIS_CELERY_DB_PASS=password
    - OASIS_CELERY_DB_USER=celery
    - OASIS_CELERY_DB_NAME=celery
    - OASIS_CELERY_DB_PORT=5432
    - OASIS_MODEL_DATA_DIRECTORY=/home/worker/model
    links:
    - celery-db
    - rabbit:myrabbit
    restart: always
    volumes:
    - ./Models/AFEQ_2019/:/home/worker/model
    - filestore-OasisData:/shared-fs:rw
    - ./data/output:/home/worker/output
  worker-crseq-2.1.2:
    build:
      context: .
      dockerfile_inline: |-
        FROM coreoasis/model_worker:2.3.5
        USER root
        RUN ln -s /home/worker/.local /root/.local
        RUN pip3 install msoffcrypto-tool openpyxl
    environment:
    - OASIS_MODEL_SUPPLIER_ID=CatRisk
    - OASIS_MODEL_ID=CRSEQ
    - OASIS_MODEL_VERSION_ID=R.2.1.1
    - OASIS_RABBIT_HOST=rabbit
    - OASIS_RABBIT_PORT=5672
    - OASIS_RABBIT_USER=rabbit
    - OASIS_RABBIT_PASS=rabbit
    - OASIS_SERVER_DB_ENGINE=django.db.backends.postgresql_psycopg2
    - OASIS_CELERY_DB_ENGINE=db+postgresql+psycopg2
    - OASIS_CELERY_DB_HOST=celery-db
    - OASIS_CELERY_DB_PASS=password
    - OASIS_CELERY_DB_USER=celery
    - OASIS_CELERY_DB_NAME=celery
    - OASIS_CELERY_DB_PORT=5432
    - OASIS_MODEL_DATA_DIRECTORY=/home/worker/model
    links:
    - celery-db
    - rabbit:myrabbit
    restart: always
    volumes:
    - ./Models/CRSEQ-2.1.2/:/home/worker/model
    - filestore-OasisData:/shared-fs:rw
    - ./data/output:/home/worker/output
  worker-crseq-nasco:
    build:
      context: .
      dockerfile_inline: |-
        FROM coreoasis/model_worker:2.3.5
        USER root
        RUN ln -s /home/worker/.local /root/.local
        RUN pip3 install msoffcrypto-tool openpyxl
    environment:
    - OASIS_MODEL_SUPPLIER_ID=CatRisk
    - OASIS_MODEL_ID=CRSEQ-NASCO
    - OASIS_MODEL_VERSION_ID=R.2.1.3
    - OASIS_RABBIT_HOST=rabbit
    - OASIS_RABBIT_PORT=5672
    - OASIS_RABBIT_USER=rabbit
    - OASIS_RABBIT_PASS=rabbit
    - OASIS_SERVER_DB_ENGINE=django.db.backends.postgresql_psycopg2
    - OASIS_CELERY_DB_ENGINE=db+postgresql+psycopg2
    - OASIS_CELERY_DB_HOST=celery-db
    - OASIS_CELERY_DB_PASS=password
    - OASIS_CELERY_DB_USER=celery
    - OASIS_CELERY_DB_NAME=celery
    - OASIS_CELERY_DB_PORT=5432
    - OASIS_MODEL_DATA_DIRECTORY=/home/worker/model
    links:
    - celery-db
    - rabbit:myrabbit
    restart: always
    volumes:
    - ./Models/CRSEQ-NASCO/:/home/worker/model
    - filestore-OasisData:/shared-fs:rw
    - ./data/output:/home/worker/output
  worker-crseq_2.1.4:
    build:
      context: .
      dockerfile_inline: |-
        FROM coreoasis/model_worker:2.3.5
        USER root
        RUN ln -s /home/worker/.local /root/.local
        RUN pip3 install msoffcrypto-tool openpyxl
    environment:
    - OASIS_MODEL_SUPPLIER_ID=CatRisk
    - OASIS_MODEL_ID=CRSEQ_2.1.4
    - OASIS_MODEL_VERSION_ID=R.2.1.4
    - OASIS_RABBIT_HOST=rabbit
    - OASIS_RABBIT_PORT=5672
    - OASIS_RABBIT_USER=rabbit
    - OASIS_RABBIT_PASS=rabbit
    - OASIS_SERVER_DB_ENGINE=django.db.backends.postgresql_psycopg2
    - OASIS_CELERY_DB_ENGINE=db+postgresql+psycopg2
    - OASIS_CELERY_DB_HOST=celery-db
    - OASIS_CELERY_DB_PASS=password
    - OASIS_CELERY_DB_USER=celery
    - OASIS_CELERY_DB_NAME=celery
    - OASIS_CELERY_DB_PORT=5432
    - OASIS_MODEL_DATA_DIRECTORY=/home/worker/model
    links:
    - celery-db
    - rabbit:myrabbit
    restart: always
    volumes:
    - ./Models/CRSEQ_2.1.4/:/home/worker/model
    - filestore-OasisData:/shared-fs:rw
    - ./data/output:/home/worker/output
  worker-crseq_2.1.5:
    build:
      context: .
      dockerfile_inline: |-
        FROM coreoasis/model_worker:2.3.5
        USER root
        RUN ln -s /home/worker/.local /root/.local
        RUN pip3 install msoffcrypto-tool openpyxl
    environment:
    - OASIS_MODEL_SUPPLIER_ID=CatRisk
    - OASIS_MODEL_ID=CRSEQ_2.1.5
    - OASIS_MODEL_VERSION_ID=R.2.1.5
    - OASIS_RABBIT_HOST=rabbit
    - OASIS_RABBIT_PORT=5672
    - OASIS_RABBIT_USER=rabbit
    - OASIS_RABBIT_PASS=rabbit
    - OASIS_SERVER_DB_ENGINE=django.db.backends.postgresql_psycopg2
    - OASIS_CELERY_DB_ENGINE=db+postgresql+psycopg2
    - OASIS_CELERY_DB_HOST=celery-db
    - OASIS_CELERY_DB_PASS=password
    - OASIS_CELERY_DB_USER=celery
    - OASIS_CELERY_DB_NAME=celery
    - OASIS_CELERY_DB_PORT=5432
    - OASIS_MODEL_DATA_DIRECTORY=/home/worker/model
    links:
    - celery-db
    - rabbit:myrabbit
    restart: always
    volumes:
    - ./Models/CRSEQ_2.1.5/:/home/worker/model
    - filestore-OasisData:/shared-fs:rw
    - ./data/output:/home/worker/output
  worker-crseq_nv:
    build:
      context: .
      dockerfile_inline: |-
        FROM coreoasis/model_worker:2.3.5
        USER root
        RUN ln -s /home/worker/.local /root/.local
        RUN pip3 install msoffcrypto-tool openpyxl
    environment:
    - OASIS_MODEL_SUPPLIER_ID=CatRisk
    - OASIS_MODEL_ID=CRSEQ_NV
    - OASIS_MODEL_VERSION_ID=R.2.1.1
    - OASIS_RABBIT_HOST=rabbit
    - OASIS_RABBIT_PORT=5672
    - OASIS_RABBIT_USER=rabbit
    - OASIS_RABBIT_PASS=rabbit
    - OASIS_SERVER_DB_ENGINE=django.db.backends.postgresql_psycopg2
    - OASIS_CELERY_DB_ENGINE=db+postgresql+psycopg2
    - OASIS_CELERY_DB_HOST=celery-db
    - OASIS_CELERY_DB_PASS=password
    - OASIS_CELERY_DB_USER=celery
    - OASIS_CELERY_DB_NAME=celery
    - OASIS_CELERY_DB_PORT=5432
    - OASIS_MODEL_DATA_DIRECTORY=/home/worker/model
    links:
    - celery-db
    - rabbit:myrabbit
    restart: always
    volumes:
    - ./Models/CRSEQ_NV/:/home/worker/model
    - filestore-OasisData:/shared-fs:rw
    - ./data/output:/home/worker/output
  worker-menaeq:
    build:
      context: .
      dockerfile_inline: |-
        FROM coreoasis/model_worker:2.3.5
        USER root
        RUN ln -s /home/worker/.local /root/.local
        RUN pip3 install msoffcrypto-tool openpyxl
    environment:
    - OASIS_MODEL_SUPPLIER_ID=CatRisk
    - OASIS_MODEL_ID=MENAEQ
    - OASIS_MODEL_VERSION_ID=R.1.2.1.G
    - OASIS_RABBIT_HOST=rabbit
    - OASIS_RABBIT_PORT=5672
    - OASIS_RABBIT_USER=rabbit
    - OASIS_RABBIT_PASS=rabbit
    - OASIS_SERVER_DB_ENGINE=django.db.backends.postgresql_psycopg2
    - OASIS_CELERY_DB_ENGINE=db+postgresql+psycopg2
    - OASIS_CELERY_DB_HOST=celery-db
    - OASIS_CELERY_DB_PASS=password
    - OASIS_CELERY_DB_USER=celery
    - OASIS_CELERY_DB_NAME=celery
    - OASIS_CELERY_DB_PORT=5432
    - OASIS_MODEL_DATA_DIRECTORY=/home/worker/model
    links:
    - celery-db
    - rabbit:myrabbit
    restart: always
    volumes:
    - ./Models/MENAEQ/:/home/worker/model
    - filestore-OasisData:/shared-fs:rw
    - ./data/output:/home/worker/output
  worker-monitor:
    command:
    - wait-for-server
    - server:8000
    - celery
    - -A
    - src.server.oasisapi
    - worker
    - --loglevel=INFO
    environment:
    - OASIS_DEBUG=1
    - OASIS_RABBIT_HOST=rabbit
    - OASIS_RABBIT_PORT=5672
    - OASIS_RABBIT_USER=rabbit
    - OASIS_RABBIT_PASS=rabbit
    - OASIS_SERVER_DB_HOST=server-db
    - OASIS_SERVER_DB_PASS=oasis
    - OASIS_SERVER_DB_USER=oasis
    - OASIS_SERVER_DB_NAME=oasis
    - OASIS_SERVER_DB_PORT=5432
    - OASIS_SERVER_DB_ENGINE=django.db.backends.postgresql_psycopg2
    - OASIS_CELERY_DB_ENGINE=db+postgresql+psycopg2
    - OASIS_CELERY_DB_HOST=celery-db
    - OASIS_CELERY_DB_PASS=password
    - OASIS_CELERY_DB_USER=celery
    - OASIS_CELERY_DB_NAME=celery
    - OASIS_CELERY_DB_PORT=5432
    image: coreoasis/api_server:2.3.5
    links:
    - server-db
    - celery-db
    - rabbit
    restart: always
    volumes:
    - filestore-OasisData:/shared-fs:rw
version: '3.4'
volumes:
  caddy_config: null
  caddy_data:
    external: true
  celery-db-OasisData: null
  filestore-OasisData: null
  server-db-OasisData: null
