services:
  broker:
    environment:
    - RABBITMQ_DEFAULT_USER=rabbit
    - RABBITMQ_DEFAULT_PASS=rabbit
    image: rabbitmq:3.8.14-management
    ports:
    - 5672:5672
    - 15672:15672
    restart: always
  caddy:
    image: caddy:latest
    ports:
    - 8080:80
    - 8000:8000
    restart: unless-stopped
    volumes:
    - ./docker/Caddyfile:/etc/caddy/Caddyfile
  celery-beat_v2:
    command:
    - celery
    - -A
    - src.server.oasisapi.celery_app_v2
    - beat
    - --loglevel=INFO
    environment:
      OASIS_CELERY_BROKER_URL: amqp://rabbit:rabbit@broker:5672
      OASIS_CELERY_DB_ENGINE: db+postgresql+psycopg2
      OASIS_CELERY_DB_HOST: celery-db
      OASIS_CELERY_DB_NAME: celery
      OASIS_CELERY_DB_PASS: password
      OASIS_CELERY_DB_PORT: 5432
      OASIS_CELERY_DB_USER: celery
      OASIS_DEBUG: 0
      OASIS_KEEP_LOCAL_DATA: 0
      OASIS_KEEP_REMOTE_DATA: 0
      OASIS_KEEP_RUN_DIR: 0
      OASIS_SERVER_CHANNEL_LAYER_HOST: channel-layer
      OASIS_SERVER_DB_ENGINE: django.db.backends.postgresql_psycopg2
      OASIS_SERVER_DB_HOST: server-db
      OASIS_SERVER_DB_NAME: oasis
      OASIS_SERVER_DB_PASS: oasis
      OASIS_SERVER_DB_PORT: 5432
      OASIS_SERVER_DB_USER: oasis
      OASIS_TASK_CONTROLLER_QUEUE: task-controller
      OASIS_URL_SUB_PATH: 1
    image: coreoasis/api_server:2.3.11
    links:
    - server-db
    - celery-db
    - broker
    restart: always
    volumes: &id001
    - filestore-OasisData:/shared-fs:rw
  celery-db:
    environment:
    - POSTGRES_DB=celery
    - POSTGRES_USER=celery
    - POSTGRES_PASSWORD=password
    image: postgres
    ports:
    - 33306:5432
    restart: always
    volumes:
    - celery-db-OasisData:/var/lib/postgresql/data:rw
  channel-layer:
    image: redis:5.0.7
    ports:
    - 6379:6379
    restart: always
  portainer:
    image: portainer/portainer:latest
    ports:
    - 8002:8002
    - 9000:9000
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./portainer_data:/data portainer/portainer
  server:
    command:
    - ./wsgi/run-wsgi.sh
    environment:
      OASIS_ADMIN_PASS: password
      OASIS_ADMIN_USER: admin
      OASIS_CELERY_BROKER_URL: amqp://rabbit:rabbit@broker:5672
      OASIS_CELERY_DB_ENGINE: db+postgresql+psycopg2
      OASIS_CELERY_DB_HOST: celery-db
      OASIS_CELERY_DB_NAME: celery
      OASIS_CELERY_DB_PASS: password
      OASIS_CELERY_DB_PORT: 5432
      OASIS_CELERY_DB_USER: celery
      OASIS_DEBUG: 0
      OASIS_KEEP_LOCAL_DATA: 0
      OASIS_KEEP_REMOTE_DATA: 0
      OASIS_KEEP_RUN_DIR: 0
      OASIS_SERVER_CHANNEL_LAYER_HOST: channel-layer
      OASIS_SERVER_DB_ENGINE: django.db.backends.postgresql_psycopg2
      OASIS_SERVER_DB_HOST: server-db
      OASIS_SERVER_DB_NAME: oasis
      OASIS_SERVER_DB_PASS: oasis
      OASIS_SERVER_DB_PORT: 5432
      OASIS_SERVER_DB_USER: oasis
      OASIS_TASK_CONTROLLER_QUEUE: task-controller
      OASIS_URL_SUB_PATH: 1
      STARTUP_RUN_MIGRATIONS: 'true'
    image: coreoasis/api_server:2.3.11
    links:
    - server-db
    - celery-db
    - broker
    ports:
    - 51970:51970
    restart: always
    volumes:
    - filestore-OasisData:/shared-fs:rw
  server-db:
    environment:
    - POSTGRES_DB=oasis
    - POSTGRES_USER=oasis
    - POSTGRES_PASSWORD=oasis
    image: postgres
    ports:
    - 33307:5432
    restart: always
    volumes:
    - server-db-OasisData:/var/lib/postgresql/data:rw
  server_websocket:
    command:
    - ./asgi/run-asgi.sh
    environment:
      OASIS_CELERY_BROKER_URL: amqp://rabbit:rabbit@broker:5672
      OASIS_CELERY_DB_ENGINE: db+postgresql+psycopg2
      OASIS_CELERY_DB_HOST: celery-db
      OASIS_CELERY_DB_NAME: celery
      OASIS_CELERY_DB_PASS: password
      OASIS_CELERY_DB_PORT: 5432
      OASIS_CELERY_DB_USER: celery
      OASIS_DEBUG: 0
      OASIS_KEEP_LOCAL_DATA: 0
      OASIS_KEEP_REMOTE_DATA: 0
      OASIS_KEEP_RUN_DIR: 0
      OASIS_SERVER_CHANNEL_LAYER_HOST: channel-layer
      OASIS_SERVER_DB_ENGINE: django.db.backends.postgresql_psycopg2
      OASIS_SERVER_DB_HOST: server-db
      OASIS_SERVER_DB_NAME: oasis
      OASIS_SERVER_DB_PASS: oasis
      OASIS_SERVER_DB_PORT: 5432
      OASIS_SERVER_DB_USER: oasis
      OASIS_TASK_CONTROLLER_QUEUE: task-controller
      OASIS_URL_SUB_PATH: 1
    image: coreoasis/api_server:2.3.11
    links:
    - server-db
    - celery-db
    - broker
    ports:
    - 8001:8001
    restart: always
    volumes:
    - filestore-OasisData:/shared-fs:rw
  user-interface:
    container_name: oasisui_app
    environment:
    - API_IP=server:8000/api/
    - API_VERSION=v2
    - API_SHARE_FILEPATH=./downloads
    - OASIS_ENVIRONMENT=oasis_localhost
    image: coreoasis/oasisui_app:1.11.7
    restart: always
  v1-worker-monitor:
    command:
    - celery
    - -A
    - src.server.oasisapi.celery_app_v1
    - worker
    - --loglevel=INFO
    environment:
      OASIS_CELERY_BROKER_URL: amqp://rabbit:rabbit@broker:5672
      OASIS_CELERY_DB_ENGINE: db+postgresql+psycopg2
      OASIS_CELERY_DB_HOST: celery-db
      OASIS_CELERY_DB_NAME: celery
      OASIS_CELERY_DB_PASS: password
      OASIS_CELERY_DB_PORT: 5432
      OASIS_CELERY_DB_USER: celery
      OASIS_DEBUG: 0
      OASIS_KEEP_LOCAL_DATA: 0
      OASIS_KEEP_REMOTE_DATA: 0
      OASIS_KEEP_RUN_DIR: 0
      OASIS_SERVER_CHANNEL_LAYER_HOST: channel-layer
      OASIS_SERVER_DB_ENGINE: django.db.backends.postgresql_psycopg2
      OASIS_SERVER_DB_HOST: server-db
      OASIS_SERVER_DB_NAME: oasis
      OASIS_SERVER_DB_PASS: oasis
      OASIS_SERVER_DB_PORT: 5432
      OASIS_SERVER_DB_USER: oasis
      OASIS_TASK_CONTROLLER_QUEUE: task-controller
      OASIS_URL_SUB_PATH: 1
    image: coreoasis/api_server:2.3.11
    links:
    - server-db
    - celery-db
    - broker
    restart: always
    volumes:
    - filestore-OasisData:/shared-fs:rw
  v2-task-controller:
    command:
    - celery
    - -A
    - src.server.oasisapi.celery_app_v2
    - worker
    - --loglevel=INFO
    - -Q
    - task-controller
    environment:
      OASIS_CELERY_BROKER_URL: amqp://rabbit:rabbit@broker:5672
      OASIS_CELERY_DB_ENGINE: db+postgresql+psycopg2
      OASIS_CELERY_DB_HOST: celery-db
      OASIS_CELERY_DB_NAME: celery
      OASIS_CELERY_DB_PASS: password
      OASIS_CELERY_DB_PORT: 5432
      OASIS_CELERY_DB_USER: celery
      OASIS_DEBUG: 0
      OASIS_KEEP_LOCAL_DATA: 0
      OASIS_KEEP_REMOTE_DATA: 0
      OASIS_KEEP_RUN_DIR: 0
      OASIS_SERVER_CHANNEL_LAYER_HOST: channel-layer
      OASIS_SERVER_DB_ENGINE: django.db.backends.postgresql_psycopg2
      OASIS_SERVER_DB_HOST: server-db
      OASIS_SERVER_DB_NAME: oasis
      OASIS_SERVER_DB_PASS: oasis
      OASIS_SERVER_DB_PORT: 5432
      OASIS_SERVER_DB_USER: oasis
      OASIS_TASK_CONTROLLER_QUEUE: task-controller
      OASIS_URL_SUB_PATH: 1
    image: coreoasis/api_server:2.3.11
    links:
    - server-db
    - celery-db
    - broker
    restart: always
    volumes:
    - filestore-OasisData:/shared-fs:rw
  v2-worker-monitor:
    command:
    - celery
    - -A
    - src.server.oasisapi.celery_app_v2
    - worker
    - --loglevel=INFO
    - -Q
    - celery-v2
    environment:
      OASIS_CELERY_BROKER_URL: amqp://rabbit:rabbit@broker:5672
      OASIS_CELERY_DB_ENGINE: db+postgresql+psycopg2
      OASIS_CELERY_DB_HOST: celery-db
      OASIS_CELERY_DB_NAME: celery
      OASIS_CELERY_DB_PASS: password
      OASIS_CELERY_DB_PORT: 5432
      OASIS_CELERY_DB_USER: celery
      OASIS_DEBUG: 0
      OASIS_KEEP_LOCAL_DATA: 0
      OASIS_KEEP_REMOTE_DATA: 0
      OASIS_KEEP_RUN_DIR: 0
      OASIS_SERVER_CHANNEL_LAYER_HOST: channel-layer
      OASIS_SERVER_DB_ENGINE: django.db.backends.postgresql_psycopg2
      OASIS_SERVER_DB_HOST: server-db
      OASIS_SERVER_DB_NAME: oasis
      OASIS_SERVER_DB_PASS: oasis
      OASIS_SERVER_DB_PORT: 5432
      OASIS_SERVER_DB_USER: oasis
      OASIS_TASK_CONTROLLER_QUEUE: task-controller
      OASIS_URL_SUB_PATH: 1
    image: coreoasis/api_server:2.3.11
    links:
    - server-db
    - celery-db
    - broker
    restart: always
    volumes:
    - filestore-OasisData:/shared-fs:rw
version: '3.4'
volumes:
  celery-db-OasisData: null
  filestore-OasisData: null
  server-db-OasisData: null
x-oasis-env-v1:
  OASIS_CELERY_DB_ENGINE: db+postgresql+psycopg2
  OASIS_CELERY_DB_HOST: celery-db
  OASIS_CELERY_DB_NAME: celery
  OASIS_CELERY_DB_PASS: password
  OASIS_CELERY_DB_PORT: 5432
  OASIS_CELERY_DB_USER: celery
  OASIS_DEBUG: ${DEBUG:-0}
  OASIS_RABBIT_HOST: broker
  OASIS_RABBIT_PASS: rabbit
  OASIS_RABBIT_PORT: 5672
  OASIS_RABBIT_USER: rabbit
x-shared-env:
  OASIS_CELERY_BROKER_URL: amqp://rabbit:rabbit@broker:5672
  OASIS_CELERY_DB_ENGINE: db+postgresql+psycopg2
  OASIS_CELERY_DB_HOST: celery-db
  OASIS_CELERY_DB_NAME: celery
  OASIS_CELERY_DB_PASS: password
  OASIS_CELERY_DB_PORT: 5432
  OASIS_CELERY_DB_USER: celery
  OASIS_DEBUG: 0
  OASIS_KEEP_LOCAL_DATA: 0
  OASIS_KEEP_REMOTE_DATA: 0
  OASIS_KEEP_RUN_DIR: 0
  OASIS_SERVER_CHANNEL_LAYER_HOST: channel-layer
  OASIS_SERVER_DB_ENGINE: django.db.backends.postgresql_psycopg2
  OASIS_SERVER_DB_HOST: server-db
  OASIS_SERVER_DB_NAME: oasis
  OASIS_SERVER_DB_PASS: oasis
  OASIS_SERVER_DB_PORT: 5432
  OASIS_SERVER_DB_USER: oasis
  OASIS_TASK_CONTROLLER_QUEUE: task-controller
  OASIS_URL_SUB_PATH: 1
x-volumes: *id001
