services:
  caddy:
    image: caddy:latest
    ports:
    - 80:80
    - 443:443
    restart: unless-stopped
    volumes:
    - ./docker/Caddyfile:/etc/caddy/Caddyfile
  celery-db:
    environment:
    - POSTGRES_DB=celery
    - POSTGRES_USER=celery
    - POSTGRES_PASSWORD=password
    image: postgres
    restart: always
    volumes:
    - celery-db-OasisData:/var/lib/postgresql/data:rw
  rabbit:
    environment:
    - RABBITMQ_DEFAULT_USER=rabbit
    - RABBITMQ_DEFAULT_PASS=rabbit
    image: rabbitmq:3.8.14-management
    restart: always
  server:
    environment:
    - OASIS_ADMIN_USER=admin
    - OASIS_ADMIN_PASS=password
    - OASIS_DEBUG=1
    - OASIS_RABBIT_HOST=rabbit
    - OASIS_RABBIT_PORT=5672
    - OASIS_RABBIT_USER=rabbit
    - OASIS_RABBIT_PASS=rabbit
    - OASIS_SERVER_DB_HOST=server-db
    - OASIS_SERVER_DB_PASS=oasis
    - OASIS_SERVER_DB_USER=oasis
    - OASIS_SERVER_DB_NAME=oasis
    - OASIS_SERVER_DB_PORT=5432
    - OASIS_SERVER_DB_ENGINE=django.db.backends.postgresql_psycopg2
    - OASIS_CELERY_DB_ENGINE=db+postgresql+psycopg2
    - OASIS_CELERY_DB_HOST=celery-db
    - OASIS_CELERY_DB_PASS=password
    - OASIS_CELERY_DB_USER=celery
    - OASIS_CELERY_DB_NAME=celery
    - OASIS_CELERY_DB_PORT=5432
    - STARTUP_RUN_MIGRATIONS=true
    image: ${SERVER_IMG:-coreoasis/api_server}:${VERS_API:-latest}
    links:
    - server-db
    - celery-db
    - rabbit
    restart: always
    volumes:
    - filestore-OasisData:/shared-fs:rw
  server-db:
    environment:
    - POSTGRES_DB=oasis
    - POSTGRES_USER=oasis
    - POSTGRES_PASSWORD=oasis
    image: postgres
    restart: always
    volumes:
    - server-db-OasisData:/var/lib/postgresql/data:rw
  ui:
    environment:
    - API_IP=server
    - API_PORT=8000
    - API_VERSION=v1
    - API_SHARE_FILEPATH=./downloads
    - OASIS_ENVIRONMENT=oasis_localhost
    image: coreoasis/oasisui_app:${VERS_UI:-latest}
    restart: always
  worker:
    environment:
    - OASIS_MODEL_SUPPLIER_ID=OasisLMF
    - OASIS_MODEL_ID=PiWind
    - OASIS_MODEL_VERSION_ID=1
    - OASIS_RABBIT_HOST=rabbit
    - OASIS_RABBIT_PORT=5672
    - OASIS_RABBIT_USER=rabbit
    - OASIS_RABBIT_PASS=rabbit
    - OASIS_SERVER_DB_ENGINE=django.db.backends.postgresql_psycopg2
    - OASIS_CELERY_DB_ENGINE=db+postgresql+psycopg2
    - OASIS_CELERY_DB_HOST=celery-db
    - OASIS_CELERY_DB_PASS=password
    - OASIS_CELERY_DB_USER=celery
    - OASIS_CELERY_DB_NAME=celery
    - OASIS_CELERY_DB_PORT=5432
    - OASIS_MODEL_DATA_DIRECTORY=/home/worker/model
    image: ${WORKER_IMG:-coreoasis/model_worker}:${VERS_WORKER:-latest}
    links:
    - celery-db
    - rabbit:myrabbit
    restart: always
    volumes:
    - ./models/OasisPiWind/:/home/worker/model
    - filestore-OasisData:/shared-fs:rw
  worker-monitor:
    command:
    - wait-for-server
    - server:8000
    - celery
    - -A
    - src.server.oasisapi
    - worker
    - --loglevel=INFO
    environment:
    - OASIS_DEBUG=1
    - OASIS_RABBIT_HOST=rabbit
    - OASIS_RABBIT_PORT=5672
    - OASIS_RABBIT_USER=rabbit
    - OASIS_RABBIT_PASS=rabbit
    - OASIS_SERVER_DB_HOST=server-db
    - OASIS_SERVER_DB_PASS=oasis
    - OASIS_SERVER_DB_USER=oasis
    - OASIS_SERVER_DB_NAME=oasis
    - OASIS_SERVER_DB_PORT=5432
    - OASIS_SERVER_DB_ENGINE=django.db.backends.postgresql_psycopg2
    - OASIS_CELERY_DB_ENGINE=db+postgresql+psycopg2
    - OASIS_CELERY_DB_HOST=celery-db
    - OASIS_CELERY_DB_PASS=password
    - OASIS_CELERY_DB_USER=celery
    - OASIS_CELERY_DB_NAME=celery
    - OASIS_CELERY_DB_PORT=5432
    image: ${SERVER_IMG:-coreoasis/api_server}:${VERS_API:-latest}
    links:
    - server-db
    - celery-db
    - rabbit
    restart: always
    volumes:
    - filestore-OasisData:/shared-fs:rw
version: '3.4'
volumes:
  caddy_config: null
  caddy_data:
    external: true
  celery-db-OasisData: null
  filestore-OasisData: null
  server-db-OasisData: null
