version: '3.4'
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - ${oasis_port}:80
      - ${admin_port}:8000
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

volumes:
  caddy_data:
    external: true
  caddy_config: