version: '3.4'
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - ${oasis_port}:80
      - ${admin_port}:8000
    volumes:
      - ./docker/Caddyfile:/etc/caddy/Caddyfile
