volumes:
  server-db-OasisData:
  celery-db-OasisData:
  filestore-OasisData:
x-shared-env: &shared-env
  OASIS_DEBUG: 0
  OASIS_KEEP_RUN_DIR: 0
  OASIS_KEEP_LOCAL_DATA: 0
  OASIS_KEEP_REMOTE_DATA: 0
  OASIS_URL_SUB_PATH: 1
  OASIS_CELERY_BROKER_URL: "amqp://rabbit:rabbit@broker:5672"
  #OASIS_CELERY_BROKER_URL: "redis://broker:6379"
  OASIS_SERVER_DB_HOST: server-db
  OASIS_SERVER_DB_PASS: oasis
  OASIS_SERVER_DB_USER: oasis
  OASIS_SERVER_DB_NAME: oasis
  OASIS_SERVER_DB_PORT: 5432
  OASIS_SERVER_CHANNEL_LAYER_HOST: channel-layer
  OASIS_SERVER_DB_ENGINE: django.db.backends.postgresql_psycopg2
  OASIS_CELERY_DB_ENGINE: db+postgresql+psycopg2
  OASIS_CELERY_DB_HOST: celery-db
  OASIS_CELERY_DB_PASS: password
  OASIS_CELERY_DB_USER: celery
  OASIS_CELERY_DB_NAME: celery
  OASIS_CELERY_DB_PORT: 5432
  OASIS_TASK_CONTROLLER_QUEUE: task-controller

x-oasis-env-v1: &oasis-env-v1
  OASIS_DEBUG: ${DEBUG:-0}
  OASIS_RABBIT_HOST: broker
  OASIS_RABBIT_PORT: 5672
  OASIS_RABBIT_USER: rabbit
  OASIS_RABBIT_PASS: rabbit
  OASIS_CELERY_DB_ENGINE: db+postgresql+psycopg2
  OASIS_CELERY_DB_HOST: celery-db
  OASIS_CELERY_DB_PASS: password
  OASIS_CELERY_DB_USER: celery
  OASIS_CELERY_DB_NAME: celery
  OASIS_CELERY_DB_PORT: 5432

x-volumes: &shared-volumes
  - filestore-OasisData:/shared-fs:rw
services:
  server:
   restart: always
   image: coreoasis/api_server:2.3.5
   command: ["./wsgi/run-wsgi.sh"]
   ports:
     - 8000:8000
     - 51970:51970
   links:
     - server-db
     - celery-db
     - broker
   environment:
     <<: *shared-env
     STARTUP_RUN_MIGRATIONS: "true"
     OASIS_ADMIN_USER: admin
     OASIS_ADMIN_PASS: password
   volumes:
     - filestore-OasisData:/shared-fs:rw
  server_websocket:
   restart: always
   image: coreoasis/api_server:2.3.5
   command: ["./asgi/run-asgi.sh"]
   links:
     - server-db
     - celery-db
     - broker
   ports:
     - 8001:8001
   environment:
     <<: *shared-env
   volumes:
     - filestore-OasisData:/shared-fs:rw
  v1-worker-monitor:
   restart: always
   image: coreoasis/api_server:2.3.5
   command: [celery, -A, 'src.server.oasisapi.celery_app_v1', worker, --loglevel=INFO,]
   links:
     - server-db
     - celery-db
     - broker
   environment:
     <<: *shared-env
   volumes:
     - filestore-OasisData:/shared-fs:rw
  v2-worker-monitor:
   restart: always
   image: coreoasis/api_server:2.3.5
   command: [celery, -A, 'src.server.oasisapi.celery_app_v2', worker, --loglevel=INFO,  -Q, celery-v2]
   links:
     - server-db
     - celery-db
     - broker
   environment:
     <<: *shared-env
   volumes:
     - filestore-OasisData:/shared-fs:rw
  v2-task-controller:
   restart: always
   image: coreoasis/api_server:2.3.5
   command: [celery, -A, 'src.server.oasisapi.celery_app_v2', worker, --loglevel=INFO, -Q, task-controller]
   links:
     - server-db
     - celery-db
     - broker
   environment:
     <<: *shared-env
   volumes:
     - filestore-OasisData:/shared-fs:rw
  celery-beat_v2:
   restart: always
   image: coreoasis/api_server:2.3.5
   command: [celery, -A, src.server.oasisapi.celery_app_v2, beat, --loglevel=INFO]
   links:
     - server-db
     - celery-db
     - broker
   environment:
     <<: *shared-env
   volumes: *shared-volumes
  server-db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=oasis
      - POSTGRES_USER=oasis
      - POSTGRES_PASSWORD=oasis
    volumes:
      - server-db-OasisData:/var/lib/postgresql/data:rw
    ports:
      - 33307:5432
  celery-db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=celery
      - POSTGRES_USER=celery
      - POSTGRES_PASSWORD=password
    volumes:
      - celery-db-OasisData:/var/lib/postgresql/data:rw
    ports:
      - 33306:5432
  broker:
    restart: always
    image: rabbitmq:3.8.14-management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    ports:
      - 5672:5672
      - 15672:15672
  channel-layer:
    restart: always
    image: redis:5.0.7
    ports:
      - 6379:6379
  user-interface:
    restart: always
    image: coreoasis/oasisui_app:${VERS_UI:-latest}
    container_name: oasisui_app
    environment:
     - API_IP=server:8000/api/
     - API_VERSION=v2
     - API_SHARE_FILEPATH=./downloads
     - OASIS_ENVIRONMENT=oasis_localhost
    ports:
     - 8080:3838
  portainer:
   restart: always
   image: portainer/portainer:latest
   ports:
     - 8002:8002
     - 9000:9000
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ./portainer_data:/data portainer/portainer        