version: '3.4'
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/Caddyfile:/etc/caddy/Caddyfile

volumes:
  caddy_data:
    external: true
  caddy_config: